# Generated by Django 5.1.2 on 2024-10-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_settings", "0002_usersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsettings",
            name="paypal_client_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="paymentsettings",
            name="paypal_client_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="paymentsettings",
            name="stripe_public_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="paymentsettings",
            name="stripe_secret_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="shippingsettings",
            name="free_shipping_threshold",
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="shippingsettings",
            name="standard_shipping_cost",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="contact_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="currency",
            field=models.CharField(default="EUR", max_length=10),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="store_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="store_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="preferred_language",
            field=models.CharField(default="en", max_length=50),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="receive_newsletter",
            field=models.BooleanField(default=True),
        ),
    ]
