# Generated by Django 5.1.2 on 2024-10-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_rename_model_name_microcontroller_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="microcontroller",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
