# Generated by Django 5.1.2 on 2024-10-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_rename_subfamily_microcontroller_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="microcontroller",
            name="sku",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
