# Generated by Django 5.1.2 on 2024-10-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_family_remove_microcontrollerfamily_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcontroller',
            name='bit_width',
            field=models.PositiveIntegerField(blank=True, choices=[(8, '8-bit'), (16, '16-bit'), (32, '32-bit'), (64, '64-bit')], null=True),
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='cpu_architecture',
            field=models.CharField(blank=True, choices=[('AVR', 'AVR'), ('ARM Cortex-M', 'ARM Cortex-M'), ('ESP32', 'ESP32'), ('ESP8266', 'ESP8266'), ('RISC-V', 'RISC-V'), ('PIC', 'PIC'), ('8051', '8051'), ('MSP430', 'MSP430')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='flash_memory_kb',
            field=models.PositiveIntegerField(blank=True, choices=[(32, '32 KB'), (64, '64 KB'), (128, '128 KB'), (256, '256 KB'), (512, '512 KB'), (1024, '1 MB'), (2048, '2 MB'), (4096, '4 MB'), (8192, '8 MB')], help_text='Flash memory capacity in KB', null=True),
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='package_type',
            field=models.CharField(blank=True, choices=[('DIP', 'Dual In-line Package (DIP)'), ('QFP', 'Quad Flat Package (QFP)'), ('BGA', 'Ball Grid Array (BGA)'), ('TSSOP', 'Thin Shrink Small Outline Package (TSSOP)'), ('SOIC', 'Small Outline IC (SOIC)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='ram_kb',
            field=models.PositiveIntegerField(blank=True, choices=[(2, '2 KB'), (32, '32 KB'), (64, '64 KB'), (128, '128 KB'), (256, '256 KB'), (512, '512 KB'), (1024, '1 MB'), (2048, '2 MB'), (4096, '4 MB')], help_text='RAM capacity in KB', null=True),
        ),
    ]
