# Generated by Django 5.1.2 on 2024-10-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_microcontroller_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_subscribed", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
