# Generated by Django 5.1.2 on 2024-10-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_newslettersignup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsletterSignup",
        ),
    ]
